### ISSUE TITLE
Upgrade to support laravel 9

### ISSUE THREAD

**Issue by yungifez** [antonioribeiro/countries#185]
Laravel 9 was released today 

And I dont think its compatible with this 

Can the compiser.json be updated to include laravel 9

**Comment by RizwanAslam** [comment]
Hey @antonioribeiro, please add support for laravel 9

**Comment by andreladocruz** [comment]
Hey @antonioribeiro, please add support for laravel 9

**Comment by BrickZ28** [comment]
@antonioribeiro any plans to add Laravel 9 support?

**Comment by gwleuverink** [comment]
I tried forking & updating the code but it seems updates to downstream `pragmarx/coollection` and `pragmarx/ia-arr` are also needed in order to support php8.1. I'd love to contribute a PR but having some trouble setting things up locally with these other dependencies. 

@antonioribeiro If you can give me a hand to set things up I'll gladly have a go at upgrading al those downstream packages

**Comment by BrickZ28** [comment]
It seems that this will die for now.  If we cant even get an in the works response or any reply from the original author then we should move one with something else and onwards to Laravel 9.  Thank you for the repo.  I hope the future you can upgrade this.

**Comment by yungifez** [comment]
I was lucky that I used it at just one place in my code

I'm planning to write a country service class in the future to prevent this from happening in the future 

I'm using a new package now and I'm running the latest laravel release

**Comment by gwleuverink** [comment]
@yungifez I'm looking for a viable alternative too. Out of curiosity, what package did you end up choosing?

**Comment by andreladocruz** [comment]
I'm using its JSON directly.

I only need the countries, currencies, and states. 

Much better than depending on a bunch dependencies.

**Comment by yungifez** [comment]
I ended up using 
https://github.com/nnjeim/world
