### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by enriqueplace** [antonioribeiro/countries#20]
Hi, 

I try with: 

$all = Countries::all();

I use:

Laravel 5.4 / PHP 7.0

The error:

(1/1) FatalErrorException
Maximum execution time of 30 seconds exceeded
in FileStore.php (line 66)

Why so long?

**Comment by antonioribeiro** [comment]
Because there's a lot of work to hydrate everything if you have border hydration enabled. The `all()` method should not be used when you have hydration enabled, because the algorithm has to recursively find every occurence of cities of adjacent countries and hydrate them all. That's why I it is disabled by default:

![image](https://user-images.githubusercontent.com/3182864/27395570-9a7f747e-5686-11e7-96f1-d66f19fbedf7.png)
