### ISSUE TITLE
Adding States

### ISSUE THREAD

**Issue by asahasrabuddhe** [antonioribeiro/countries#43]
Hello @antonioribeiro ,

Thanks for this awesome effort you have put to create this package. Kudos! I am trying to use this library in one of my projects and I have found that some data is currently missing.

I want to help myself out and in process also help you and the entire community at large by filling in the blanks where ever possible.

I have here a list of countries without states:

> ALA Åland Islands
> 
> ATG Antigua and Barbuda
> 
> BEL Belgium
> 
> BIH Bosnia and Herzegovina
> 
> ESH Western Sahara
> 
> IRQ Iraq
> 
> UNK Kosovo
> 
> NOR Norway
> 
> PNG Papua New Guinea
> 
> PRT Portugal
> 
> PSE Palestine
> 
> SJM Svalbard and Jan Mayen
> 
> SOM Somalia
> 
> SRB Serbia
> 
> SSD South Sudan
> 
> SYR Syria
> 
> UMI United States Minor Outlying Islands

I have a database with me that has the list of states for the above countries. Could you please guide me as to what convention have you used to generate the state json data? What is the purpose of each field and how I can fill them out with proper and correct data?

Looking forward for your response. Thanks a lot.

Regards,
Ajitem

**Comment by antonioribeiro** [comment]
This package is, as a matter of fact, a collection of some other packages, encapsulated to make it easy to get the data we need from it. States, specifically, are read from the [natural-earth-vector](https://github.com/nvkelso/natural-earth-vector/tree/master/10m_cultural) repository, and I'm not really judging it, nor have a complete knowledge of all fields it provides, but I'm sure they will make sense for a lot of people since the library is being used by NaturalEarthData.com.

My opinion about your matter is that you should first ask them to add the missing states, or send them a a pull request adding them.

**Comment by asahasrabuddhe** [comment]
Awesome! Thanks a lot. I will look into this further.

**Comment by antonioribeiro** [comment]
Issue opened in their repository: https://github.com/nvkelso/natural-earth-vector/issues/240

**Comment by antonioribeiro** [comment]
Except for

**Comment by antonioribeiro** [comment]
They are all correct now. I was using the wrong country code, those ones are also present in the database, but their country codes are not matching with yours

[adm0_a3] => ALD   !==   ALA
[adm0_a3] => SAH   !==   ESH
[adm0_a3] => NOR   !==  SJM 
[adm0_a3] => SDS   !==  SSD

And we still have a missing one: Palestine

**Comment by antonioribeiro** [comment]
We can now use the `overload states` feature to add missing states or change wrong ones, as an example I added some for Palestine: 

https://github.com/antonioribeiro/countries/blob/master/src/data/states/overload/pse.json
